# Target Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-2a-dotprod
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_VARIANT := cortex-a76

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := cortex-a76

# Graphics & Display
BOARD_GPU_DRIVERS := v3d vc4
TARGET_USES_VULKAN := true
BOARD_USES_DRM_HWCOMPOSER := true
TARGET_USES_HWC2 := true
BOARD_EGL_WORKAROUND_BUG_1019066 := true

# SEPolicy
BOARD_SEPOLICY_DIRS += device/rpi/rpi5/sepolicy
PRODUCT_FULL_TREBLE_OVERRIDE := true

# Kernel Configuration
BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_PAGESIZE := 4096
BOARD_KERNEL_CMDLINE := console=ttyAMA0,115200 rootwait androidboot.hardware=rpi5 androidboot.selinux=permissive
BOARD_INCLUDE_RECOVERY_DTBO := false
BOARD_USES_GENERIC_KERNEL_IMAGE := false

# Filesystem & Partition Layout
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_FLASH_BLOCK_SIZE := 4096

# Output Directory Mapping (Wajib ada di AOSP 15)
TARGET_COPY_OUT_VENDOR := vendor
TARGET_COPY_OUT_PRODUCT := product
TARGET_COPY_OUT_SYSTEM_EXT := system_ext

# Ukuran Partisi Statis
BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864          # 64MB
BOARD_USERDATAIMAGE_PARTITION_SIZE := 1073741824    # 1GB

# Ukuran Partisi Individual (Mencegah KeyError di build_image.py)
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2147483648      # 2GB
BOARD_VENDORIMAGE_PARTITION_SIZE := 536870912       # 512MB
BOARD_PRODUCTIMAGE_PARTITION_SIZE := 536870912      # 512MB
BOARD_SYSTEM_EXTIMAGE_PARTITION_SIZE := 268435456   # 256MB

# Dynamic Partitions (Super Image - 4GB)
BOARD_SUPER_PARTITION_SIZE := 4294967296
BOARD_SUPER_PARTITION_GROUPS := rpi5_dynamic_partitions
BOARD_RPI5_DYNAMIC_PARTITIONS_SIZE := 4290772992
BOARD_RPI5_DYNAMIC_PARTITIONS_PARTITION_LIST := system system_ext product vendor

# Tipe Filesystem
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEM_EXTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4