TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-2a-dotprod
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_VARIANT := cortex-a76

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := cortex-a76

TARGET_NO_KERNEL := false
BOARD_KERNEL_IMAGE_NAME := Image.gz
BOARD_BOOT_HEADER_VERSION := 2
BOARD_KERNEL_CMDLINE := console=tty1 console=ttyAMA0,115200 root=/dev/ram0 initrd=0x03000000 androidboot.hardware=rpi5 androidboot.selinux=permissive

BOARD_SUPER_PARTITION_SIZE := 4294967296
BOARD_SUPER_PARTITION_GROUPS := rpi_dynamic_partitions
BOARD_RPI_DYNAMIC_PARTITIONS_SIZE := 4290772992
BOARD_RPI_DYNAMIC_PARTITIONS_PARTITION_LIST := system vendor product system_ext

TARGET_USERIMAGES_USE_EXT4 := true
BOARD_USERDATAIMAGE_PARTITION_SIZE := 4294967296
BOARD_FLASH_BLOCK_SIZE := 4096

BOARD_USES_MINIGBM := true
BOARD_GPU_DRIVERS := v3d vc4
TARGET_USES_VULKAN := true

BOARD_SEPOLICY_DIRS += device/rpi/rpi5/sepolicy